site_name: ExplorePinas
copyright: 'copyright © ExplorePinas, LTD, All rights reserved.'
theme:
  name: 'material'
  palette:
    primary: indigo
    accent: indigo
pages:
    - Overview: /
    - About: about.md
    - Coding Conventions:
      - Front End: coding_conventions/front_end_convention.md
      - Back End: coding_conventions/back_end_convention.md
    - Infrastructure:
      - Chart: infra/chart.md
      - Use Case: infra/use_case.md
    - Mock-ups:
      - Homepage: mockups/homepage.md
